import { AppConfig } from './schema';

export const DEFAULT_CONFIG: AppConfig = {
  system: {
    mode: 'dry-run',
    logLevel: 'info',
    serviceName: 'bc-game-crash-automation',
  },
  betting: {
    stakePerEntry: 700,
    cashOutTarget: 1.30,
    maxDailyEntries: 100,
    currencyUnit: 'units',
    dayBoundaryTimezone: 'UTC',
  },
  risk: {
    minBalanceForEntry: 700,
    balanceBuffer: 700,
    maxConsecutiveErrorsBeforeStop: 3,
    maxCashOutFailuresBeforeStop: 2,
    cooldownMs: 5000,
    minPredictionProbability: 0.35,
    minPredictionConfidence: 0.3,
    requirePredictionForLive: true,
  },
  observation: {
    maxTickLatencyMs: 1000,
    minConfidenceForEntry: 'high',
    requireRoundId: true,
    latencyThresholdHealthyMs: 500,
    latencyThresholdDegradedMs: 1000,
  },
  telegram: {
    allowedUserIds: [],
    verbosity: 'normal',
    sendRoundStart: false,
    sendRoundResult: true,
    sendHealthWarnings: true,
    rateLimitMessagesPerMinute: 30,
  },
  browser: {
    headless: false,
    viewportWidth: 1366,
    viewportHeight: 900,
    profileDirectory: './secrets/browser-profile',
    timeoutMs: 30000,
    stealth: {
      enabled: true,
      preferNonHeadlessForLive: true,
      disableAutomationControlled: true,
      canvasNoise: true,
      webglNoise: true,
      audioNoise: true,
    },
    interaction: {
      humanize: true,
      minActionDelayMs: 70,
      maxActionDelayMs: 450,
      mouseBezier: true,
      typeInsteadOfFill: true,
      requirePrecedingMouseMove: true,
    },
    session: {
      maxAgeHours: 12,
      maxContinuousActiveMinutes: 150,
      rotationJitterMinutes: 25,
      warmUpNavigation: true,
      quarantineOnChallenge: true,
      minWarmStandbyProfiles: 1,
    },
    network: {
      proxyServer: null,
      proxyMatchTimezone: true,
    },
    canaryIntervalMs: 30000,
    unknownReconciliationTimeoutMs: 300000,
  },
  persistence: {
    databasePoolSize: 10,
    redisCommandTimeoutMs: 5000,
    redisReconnectIntervalMs: 3000,
  },
  health: {
    checkIntervalMs: 30000,
    degradationThreshold: 2,
    failureThreshold: 3,
  },
  proxy: {
    enabled: false,
    sticky: true,
    rotationMode: 'never',
    provider: 'generic',
  },
  velocity: {
    enabled: true,
    minActionIntervalMs: 8000,
    maxActionIntervalMs: 25000,
    maxActionsPerMinute: 4,
    maxActionsPerHour: 60,
    idleProbability: 0.12,
    minIdleMs: 30000,
    maxIdleMs: 180000,
    cashOutJitterMs: 180,
  },
  behavioral: {
    enabled: true,
    mouseStepsMin: 8,
    mouseStepsMax: 22,
    mouseOvershootPx: 12,
    clickDelayMinMs: 35,
    clickDelayMaxMs: 130,
    typeDelayMinMs: 30,
    typeDelayMaxMs: 95,
  },
  telemetryNoise: {
    enabled: false,
    cashOutTargetNoise: 0.015,
    skipEntryProbability: 0.04,
    delayedCashOutProbability: 0.03,
  },
  sessionConsistency: {
    maxSessionAgeHours: 72,
    requireAuthOnStart: true,
    pauseOnAuthLoss: true,
    profileSticky: true,
  },
  specUpgrade: {
    ja4: { enabled: true, profileId: 'chrome-126-win11' },
    nativeSocket: {
      enabled: true,
      noDelay: true,
      sendBufferSize: 262144,
      recvBufferSize: 262144,
      heartbeatIntervalMs: 15000,
      safetyMarginMs: 15,
      preSendEnabled: true,
    },
    payloadIngestion: { enabled: true, circuitBreakerThreshold: 8 },
    provablyFair: {
      enabled: true,
      maxHashFailures: 3,
      kellyLambda: 0.25,
      kellyMaxFraction: 0.05,
      volatilitySigmaThreshold: 3,
      turnoverMode: false,
      turnoverTarget: 1.01,
    },
    capital: {
      enabled: true,
      hotBuffer: 5000,
      withdrawThreshold: 8000,
      minWithdrawAmount: 1000,
      sweepCooldownMs: 300000,
      maxDrawdownAbs: 5000,
      maxDrawdownPct: 0.25,
      panicBalanceFloor: 500,
      watchdogEnabled: true,
      watchdogPollIntervalMs: 10000,
    },
    stealth: {
      hardwareProfileId: 'win11-rtx3060-chrome',
      biomechanicalInput: true,
      protocolOffload: true,
    },
    settlement: {
      enabled: true,
      driftThreshold: 0.0001,
      driftPollIntervalMs: 30000,
      driftEnabled: true,
      evidenceProvider: 'null',
    },
  },
};
